const waterPreparationList = [
  {
    leak: 'false',
    consumption: "1234",
    checkClock: 'true',
    pressureIn: '6,5',
    pressureM1: "4,5",
    pressureM2: "4,5",
    // pressureM3: ,
    // pressureM4: ,
    rw: "500",
    // conc: ,
    permeate: '4',
    temp: '20,4',
    rj: '99,3',
    pressureMO2: '9,1',
    pressureMO3: '8,0',
    pressureMO4: '8,2',
    pressureMO5: '4,1',
    flushingFilter: 'true',
    dg: 'true',
    salt: 'true',
    errOsmos: 'false',
    errHotDisinfection: 'false',
    errCSS: 'false',
    descripton: '',
    owner: '222222',
    center: 'Солнцево',
    date: '23-09-23',
    _id: '12345',
  },
  {
    leak: 'false',
    consumption: "1245",
    checkClock: 'true',
    pressureIn: '6,4',
    pressureM1: "4,4",
    pressureM2: "4,4",
    // pressureM3: ,
    // pressureM4: ,
    rw: "523",
    // conc: ,
    permeate: '3',
    temp: '21,4',
    rj: '99,7',
    pressureMO2: '9,0',
    pressureMO3: '8,2',
    pressureMO4: '8,1',
    pressureMO5: '4,6',
    flushingFilter: 'true',
    dg: 'true',
    salt: 'true',
    errOsmos: 'false',
    errHotDisinfection: 'false',
    errCSS: 'false',
    descripton: '',
    owner: '111111',
    center: 'Солнцево',
    date: '24-09-23',
    _id: '12346',
  },
  {
    leak: 'false',
    consumption: "1256",
    checkClock: 'true',
    pressureIn: '6,5',
    pressureM1: "4,5",
    pressureM2: "4,5",
    // pressureM3: ,
    // pressureM4: ,
    rw: "500",
    // conc: ,
    permeate: '4',
    temp: '20,4',
    rj: '99,3',
    pressureMO2: '9,1',
    pressureMO3: '8,0',
    pressureMO4: '8,2',
    pressureMO5: '4,1',
    flushingFilter: 'true',
    dg: 'true',
    salt: 'true',
    errOsmos: 'false',
    errHotDisinfection: 'false',
    errCSS: 'false',
    descripton: '',
    owner: '222222',
    center: 'Солнцево',
    date: '25-09-23',
    _id: '12347',
  },
  {
    leak: 'false',
    consumption: "1267",
    checkClock: 'true',
    pressureIn: '6,7',
    pressureM1: "4,7",
    pressureM2: "4,7",
    // pressureM3: ,
    // pressureM4: ,
    rw: "567",
    // conc: ,
    permeate: '6',
    temp: '25,5',
    rj: '99,9',
    pressureMO2: '9,5',
    pressureMO3: '8,4',
    pressureMO4: '8,7',
    pressureMO5: '4,5',
    flushingFilter: 'true',
    dg: 'true',
    salt: 'true',
    errOsmos: 'true',
    errHotDisinfection: 'false',
    errCSS: 'false',
    descripton: 'Ошибка А16 в 7:44',
    owner: '111111',
    center: 'Солнцево',
    date: '26-09-23',
    _id: '12348',
  }
];

export default waterPreparationList;