const partsList = [
  {
    partNumber: "aaa111",
    partName: "Насос",
    center: "ЦС",
    propose: "АИП",
    installedOn: "",
    _id: "0001",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "13-11-23",
  }, {
    partNumber: "aaa112",
    partName: "блок",
    center: "ЦС",
    propose: "Другое",
    installedOn: "",
    _id: "0002",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "12-11-23",
  }, {
    partNumber: "aaa113",
    partName: "Датчик",
    center: "Солнцево",
    propose: "АИП",
    installedOn: "",
    _id: "0003",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "10-11-23",
  }, {
    partNumber: "aaa114",
    partName: "Крышка",
    center: "Солнцево",
    propose: "АИП",
    installedOn: "",
    _id: "0004",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "12-11-23",
  }, {
    partNumber: "aaa115",
    partName: "Коннектор",
    center: "ЦС",
    propose: "АИП",
    installedOn: "",
    _id: "0005",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "13-11-23",
  }, {
    partNumber: "aaa116",
    partName: "Шланг",
    center: "ЦС",
    propose: "АИП",
    installedOn: "",
    _id: "0006",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "09-11-23",
  }, {
    partNumber: "aaa117",
    partName: "Мотор",
    center: "ЦС",
    propose: "АИП",
    installedOn: "",
    _id: "0007",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "08-11-23",
  }, {
    partNumber: "aaa118",
    partName: "Винт",
    center: "ЦС",
    propose: "АИП",
    installedOn: "",
    _id: "0008",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "13-11-23",
  }, {
    partNumber: "aaa119",
    partName: "Шайба",
    center: "ЦС",
    propose: "АИП",
    installedOn: "",
    _id: "0009",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "13-11-23",
  }, {
    partNumber: "aaa119",
    partName: "Шайба",
    center: "ЦС",
    propose: "АИП",
    installedOn: "",
    _id: "0010",
    owner: "222222",
    ownerName: "Кларк Кент",
    date: "13-11-23",
  },
];

export default partsList